pipeline {
    agent any

    stages {
        stage("build") {
            steps {
                echo "mvn clean package"
            }
        }

        post {
            success {
                archiveArtifacts artifacts: '**/target/*.war'
            }
}
    }
}